sudo: required
language: generic
services:
 - docker
env:
 - HHVM_VERSION=3.15-lts-latest
 - HHVM_VERSION=3.18-lts-latest
 - HHVM_VERSION=latest
script:
 - docker pull hhvm/hhvm:$HHVM_VERSION
 - docker run -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION /var/source/.travis.sh
